openapi: 3.0.4
info:
  title: Bataille NavAPI
  description: |-
    Une API pour jouer à la bataille navale sur un serveur

  contact:
    email: apiteam@fansdebackend.io
  license:
    name: GPLv3
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0

tags:
  - name: pet
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: https://swagger.io
  - name: play
    description: Allows you to play a game
  - name: watch
    description: Allows you to watch a game played by others

paths:
  /play/create:
    get:
      tags:
        - play
      description: Creates a game
      responses:
        '200':
          description: ID of the created game
          content:
            string:
              schema:
                type: string
                example: 0196f8d6-582f-7000-9d15-d208a97d25fd

  
  /play/{gameId}/fire:
    post:
      tags:
       - play
      description: Shoot on a point
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: string
            example: 0196fdf3-93b1-7000-93c0-5249c1710d41
      requestBody:
        content:
          json:
            schema:
              type: object
              properties:
                x:
                  type: integer
                  example: 4
                y:
                  type: integer
                  example: 8
                player:
                  description:  uuid du joueur
                  type: string
                  example: 0196fdf3-93b1-7000-93c0-5249c1710d41

      responses:
        '200':
          description: Shot was at valid coordinates
          content:
            json:
              schema:
                type: object
                properties:
                  kill:
                    type: boolean
                    example: false
                  hit:
                    type: boolean
                    example: true


  /play/join:
    get:
      tags: 
        - play
      description: A MODIFIER PAR Zéphyr !!!  Allows you to join an existing game. 
      parameters:
        - in: query
          name: gameId
          schema:
            type: string
          required: true
          description: The ID of the game you want to join.
      
      responses:
        '200':
          description: Connection successful
          headers:
            Set-Cookie: 
              schema:
                type: string
              description: A UID to identify you for the current game
        
        '404':
          description: The requested game has not been found

        '409':
          description: There is no place left in this game
      
            


